services:
  consul:
    image: consul:1.15.4
    container_name: rms-consul
    ports:
      - '${CONSUL_PORT:-8500}:8500'
      - '8300:8300'
      - '8600:8600'
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
    networks:
      - rms-network
    labels:
      org.springframework.boot.ignore: true

  consul-config-loader:
    image: jhipster/consul-config-loader:v0.4.1
    container_name: rms-consul-config-loader
    volumes:
      - ./src/main/docker/central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - rms-network
    labels:
      org.springframework.boot.ignore: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: rms-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '${ELASTICSEARCH_PORT:-9200}:9200'
    networks:
      - rms-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: rms-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - rms-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: rms-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rms-network

  postgresql:
    image: postgres:17
    container_name: rms-postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: rms
      POSTGRES_USER: rms
      POSTGRES_PASSWORD: rms
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - rms-network

networks:
  rms-network:
    driver: bridge

volumes:
  postgresql_data:
