version: '3.8'
services:
  config-server:
    image: hyness/spring-cloud-config-server:4.1.3
    container_name: config-server
    ports:
      - '8888:8888'
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/your-org/rms-config-repo.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
      - SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START=true
    volumes:
      - ./config-repo:/config-repo
    networks:
      - rms-network

networks:
  rms-network:
    driver: bridge
