version: '3.8'
services:
  postgresql:
    image: postgres:15
    container_name: rms-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=rms
      - POSTGRES_USER=rms
      - POSTGRES_PASSWORD=rms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
